services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=Etc/UTC
    volumes:
      - /opt/jellyfin/data:/config
      - /mnt/data/series:/data/tvshows
      - /mnt/data/movies:/data/movies
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    restart: unless-stopped
